---
namespace: mariadb-cluster

stack:
  defines: process-group
  metadata:
    name: mariadb
    description: |
      MariaDB is a popular open-source relational database management system (RDBMS) that is compatible with MySQL.
      It was initially created as a fork of MySQL in 2009 by the original developers of }/mariadb-conf:/etc/mysql/conf.d
      MariaDB offers many additional features and enhancements over MySQL, including improved performance, scalability, and security.
      It also includes several advanced features such as support for dynamic columns, parallel replication, and built-in support for geographic information system (GIS) data.
    tags: stored procedures, triggers, self hosted, query optimization, mysql alternative, database, replication, clustering
    website: https://mariadb.org/
    source: https://github.com/MariaDB/
    publisher: monk.io
    icon: https://www.vectorlogo.zone/logos/mariadb/mariadb-ar21.png
  runnable-list:
    - mariadb-cluster/master
    - mariadb-cluster/slave1
    - mariadb-cluster/slave2
    - mariadb-cluster/configure
  variables:
    mariadb_database_repl_user:
      value: repl
      type: string
    mariadb_database_repl_password:
      value: RhgDPXPEnAgJ5q5g
      type: string
    mariadb_database_monitor_user:
      value: monitor
      type: string
    mariadb_database_monitor_password:
      value: RhgDPXPEnAgJ5q5g
      type: string
    mariadb_database_user:
      value: db_user
      type: string
    mariadb_database_root_password:
      value: RhgDPXPEnAgJ5q5g
      type: string
    mariadb_database_name:
      value: monk
      type: string
    mariadb_database_password:
      value: RhgDPXPEnAgxxXYZ
      type: string
    mariadb_image_tag:
      value: 'latest'
      type: string
