namespace: mariadb-cluster

stack:
  defines: process-group
  runnable-list:
    - mariadb-cluster/master
    - mariadb-cluster/slave1
    - mariadb-cluster/slave2
    - mariadb-cluster/configure
  variables:
    mariadb_database_repl_user:
      value: repl
      type: string
    mariadb_database_repl_password:
      value: RhgDPXPEnAgJ5q5g
      type: string
    mariadb_database_monitor_user:
      value: monitor
      type: string
    mariadb_database_monitor_password:
      value: RhgDPXPEnAgJ5q5g
      type: string
    mariadb_database_user:
      value: db_user
      type: string
    mariadb_database_root_password:
      value: RhgDPXPEnAgJ5q5g
      type: string
    mariadb_database_name:
      value: monk
      type: string
    mariadb_master_database_port: 3306
    mariadb_slave1_database_port: 3307
    mariadb_slave2_database_port: 3308
    mariadb_database_password: RhgDPXPEnAgxxXYZ
    mariadb_image_tag:
      value: '10.10'
      type: string
    mariadb_database_data_volume_path:
      value: <- `${moncc-volume-path}/mariadb`
      type: string
    mariadb_database_data_volume_size: 60
