namespace: mariadb

stack:
  defines: process-group
  runnable-list:
    - mariadb/mariadb
  variables:
    mariadb-image-tag: latest
    mariadb-root-password: 4wfoA7auxY
    mariadb-database-name: mariadb
    mariadb-user-name: mariadbuser
    mariadb-user-password: Cz9mGzmRtW
