namespace: mariadb-ha

stack:
  defines: process-group
  metadata:
    defines: metadata
    name: mariadb
    description: MariaDB Galera is a multi-primary database cluster solution for synchronous replication and high availability.
    tags: self hosted, database
    website: https://mariadb.org/
    source: https://github.com/MariaDB/
    publisher: "monk.io"
    icon: https://raw.githubusercontent.com/docker-library/docs/fe985dcb24154456254e252d1fa4a2b6b656ee80/mariadb/logo.png
  runnable-list:
    - mariadb-ha/mariadb-bootstrap
    - mariadb-ha/monk-slave-1
    - mariadb-ha/monk-slave-2
  variables:
    mariadb-image-tag: latest
    mariadb-root-user: root
    mariadb-root-password: thisismyrootpassword
    mariadb-database-name: mydatabasename
    mariadb-user-name: myuser
    mariadb-user-password: thisismyuserpassword
    mariadb-cluster-name: my_galera 
    mariadb-mariabackup-user: my_mariabackup_user 
    mariadb-mariabackup-password: cNQAW4GT
    mariadb-replication-user: my_replication_user
    mariadb-replication-password: FDkxXPB7


    